### ISSUE TITLE
Utilização do objeto URL para lidar com urls e parametros

### ISSUE THREAD

**Issue by eualex** [euviniciuss/cl-pinterest#1]
Quando estamos lidando com url e alguns parâmetros comumente partimos para uma abordagem com string e objetos para gerenciar os parâmetros, o que não é errado, mas existe uma maneira delicinha de lidar com url's também.

Follow the code:

```typescript
const url = new URL('https://api.thecatapi.com/v1/images/search')
url.searchParams.set('limit', '30')
url.searchParams.set('auth', 'my_auth_token')

// 'https://api.thecatapi.com/v1/images/search?limit=30&auth=my_auth_token'
url.toString()
```

**Comment by euviniciuss** [comment]
Muito interessante esta maneira de gerenciar parâmetros na URL!

Gostei muito da sugestão, ela já foi implementada no código!

Obrigado
